### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dnsmnds**
- add PostgreSQL and Gradle version;
- update Docker command to run PostgreSQL image.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
The image used should just be the latest, so remove the `:9.4` part

**Comment by jesperpedersen** [comment]
Please, squash and rebase

**Comment by dnsmnds** [comment]
Jesper, I did fixes above as you said.

**Comment by jesperpedersen** [comment]
Thanks !

**Pull request merged**
