### PR TITLE
add checkstyle config

### PR DESCRIPTION
**Pull request by dnsmnds**
- add gradle checkstyle plugin
- update ShapeRepository.java with sample header
- update README with instructions about Checkstyle

### CODE REVIEW

**Comment by jesperpedersen** [comment]
checkstyle should be run before compile

**Comment by dnsmnds** [comment]
Hi Jesper,

Do you mean that should be run before compileJava task?

**Comment by jesperpedersen** [comment]
Yeah, I'll take a deeper look tomorrow on your PR

**Comment by jesperpedersen** [comment]
Yeah, good start.

Remove the changes to README.md, and the file header.java.

Good that you have `AvoidStarImport`, but I think we need to sort our imports as well

* com.cellar
* java
* javax
* org
* Rest

I think we can remove `FinalParameters`, `FinalClass`, `MagicNumber` as they are annoying.

Bump LineLength to 120 characters.

We probably need
* ignoreConstructorParameter
* ignoreSetter
for `HiddenField`.

Please, rebase and squash

**Comment by dnsmnds** [comment]
Do you think `sortImportsInGroupAlphabetically` to sort our imports is good enough by now?

Source: https://checkstyle.sourceforge.io/config_imports.html

**Comment by jesperpedersen** [comment]
`ImportOrderCheck` - https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.html

**Comment by pauldpearson** [comment]
Can this be merged? @jesperpedersen

**Comment by jesperpedersen** [comment]
Lets wait until it is passing, and part of the build

**Comment by dnsmnds** [comment]
> Yeah, good start.
> 
> Remove the changes to README.md, and the file header.java.
> 
> Good that you have `AvoidStarImport`, but I think we need to sort our imports as well
> 
> * com.cellar
> * java
> * javax
> * org
> * Rest
> 
> I think we can remove `FinalParameters`, `FinalClass`, `MagicNumber` as they are annoying.
> 
> Bump LineLength to 120 characters.
> 
> We probably need
> 
> * ignoreConstructorParameter
> * ignoreSetter
> 
> for `HiddenField`.
> 
> Please, rebase and squash

Hi @jesperpedersen, I did above changes. Please let me know if it needs more changes in.

**Comment by jesperpedersen** [comment]
I have merged this PR. Please, make sure that you are rebased and have squashed commits,

Thanks for your contribution !

We will enable checkstyle for compile once all failures have been resolved. Working on a class -> fix its checkstyle failures as part of the commit.

**Pull request closed without merging**
