### PR TITLE
add user service unit test

### PR DESCRIPTION
**Pull request by dnsmnds**
I'm adding an user service unit test then I needed to change few classes to get that properly working. 

I needed to add `@Validated` and `@Valid` annotation in `UserDto` and `UserService` to allow Spring Boot to make validation works properly and allow me to do an unit test as well. 

I didn't all tests because I want to know that pull request is going to be approved if so I'll go to keep working on `UserServiceUnitTest` to cover my use cases. 

Any questions feel free to ask me :)

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Keep going at it - tests are meant to find issues :)

Be sure to use `./gradlew check` to verify checkstyle and test cases

**Comment by dnsmnds** [comment]
Cool! I'll do, thanks Jesper.

**Comment by dnsmnds** [comment]
I added all tests regarding to user register @jesperpedersen. 

You can see there are two methods which it was duplicated but it was important to cover all use cases about user register. I'll work on removing those two methods after this PR getting approved. 
Those methods (i.e.,` emailExists` and `usernameExists`)  are in `RegistrationController.java` and also now in `UserServiceImpl.java` then I'll remove those in `RegistrationController.java` because they are not more useful there but as I said before that is going to be on another issue I'll open after that PR getting approved. 

Please any doubt let me know :)

**Comment by jesperpedersen** [comment]
Merged.

I don't know if we should use RuntimeException as the base, but lets look at that separately.

Thanks !

**Pull request closed without merging**
